#ifndef _PIN_INCLUDE
#define _PIN_INCLUDE

/* MOVE */
#define PIN_MOVE_LSPEED 5
#define PIN_MOVE_LIN 6
#define PIN_MOVE_LOUT 7
#define PIN_MOVE_RIN 8
#define PIN_MOVE_ROUT 9
#define PIN_MOVE_RSPEED 10

/* SHOOTER */
#define PIN_SHOOTER_IN 4
#define PIN_SHOOTER_OUT 2
#define PIN_SHOOTER_SPEED 3

/* DISTANCE */
#define PIN_DISTANCE_TRIG 11
#define PIN_DISTANCE_ECHO A0

/* BLUETOOTH */
#define PIN_BT_TX 13
#define PIN_BT_RX 12

#endif